# Generated by Django 5.2.9 on 2026-02-21 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0001_initial"),
        ("rack", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="rack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="rack.rack",
            ),
        ),
    ]
