# Generated by Django 5.2.9 on 2026-02-22 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0003_device_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="rack",
        ),
    ]
