# Generated by Django 5.2.9 on 2026-02-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rack", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rack",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
