# Generated by Django 5.2.9 on 2026-02-22 09:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0003_device_deleted_at"),
        ("rack", "0002_rack_deleted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="RackUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creations"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification"
                    ),
                ),
                (
                    "unit",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rack_units",
                        to="device.device",
                    ),
                ),
                (
                    "rack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rack_units",
                        to="rack.rack",
                    ),
                ),
            ],
            options={
                "ordering": ("rack", "unit"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rack", "unit"), name="unique_rack_unit"
                    )
                ],
            },
        ),
    ]
